version: "3.3"
services:
  app:
    image: artcode/spring-college-docker
    build: ./src/main/java/artcode/springcollegedocker/docker
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: vadym
      DATABASE_NAME: springdocker
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0.20
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/springdocker
      MYSQL_ROOT_PASSWORD: 1595
      MYSQL_DATABASE: springdocker
      MYSQL_USER: vadym
      MYSQL_PASSWORD: 1595






